// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmtuuslqgcqyitqykxub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdHV1c2xxZ2NxeWl0cXlreHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTY4NDUsImV4cCI6MjA2MzczMjg0NX0.qHCu8fRk_ifLNj7Caggxmdx9ZBtboiOADWedewHbKns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);